Add Exact TN to docs
PennyLaneAI/pennylane-lightning pull request #1021
Opened 2024-12-09 15:38 UTC by multiphaseCFD

### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      [`tests`](../tests) directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] Ensure that code is properly formatted by running `make format`. 

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2024-12-09 22:02 UTC, maliasadi requested changes
Thanks @multiphaseCFD! Ping me for the second round :slightly_smiling_face:

2024-12-09 22:02 UTC, maliasadi commented on doc/lightning_tensor/device.rst
> +Note that as ``lightning.tensor`` cannot cleaned up the data with `reset()` like other state-vector devices. It is recommended to create a new ``lightning.tensor`` device per circuit to ensure resour
Doesn't reset have any docstring?
![image](https://github.com/user-attachments/assets/38688777-0b68-4708-abd2-8bfb8c11e959)
 
```suggestion
Note that as ``lightning.tensor`` cannot cleaned up the data with ``reset()`` like other state-vector devices. It is recommended to create a new ``lightning.tensor`` device per circuit to ensure resources are correctly handled.
```

2024-12-10 15:33 UTC, multiphaseCFD commented on doc/lightning_tensor/device.rst
> +The ``lightning.tensor`` device is designed for expectation value calculations. Measurements of ``qml.probs()`` or ``qml.state()`` return dense vectors of dimension :math:`2^{n_\text{qubits}}`, so th
Nice one!

2024-12-11 19:06 UTC, maliasadi approved these changes
LGTM! :star:  We need one more approval from @DSGuala or @AntonNI8 to merge the PR.

2024-12-11 19:06 UTC, maliasadi commented on doc/lightning_tensor/device.rst
> +and greater. This device supports both exact and finite shots measurements. Currently, the supported differentiation methods are parameter-shift and finite-diff. Note that the MPS backend of lightnin
```suggestion
and greater. This device supports both exact and finite shots measurements. Currently, the supported differentiation methods are parameter-shift and finite-diff. Note that the MPS backend of ``lightning.tensor`` supports multi-wire gates via Matrix Product Operators (MPO).
```

2024-12-11 19:06 UTC, maliasadi commented on doc/lightning_tensor/device.rst
> +Users can not create a :class:`~pennylane.ops.op_math.Sum` observable or a :class:`~pennylane.ops.op_math.Prod` observable from :class:`~pennylane.ops.op_math.Sum` observables.
:+1:

2024-12-13 18:32 UTC, AntonNI8 commented on doc/lightning_tensor/device.rst
> +A ``lightning.tensor`` device is defaulted by the Matrix Product State (MPS) method and can be loaded simply using:
```suggestion
The ``lightning.tensor`` device defaults to the Matrix Product State (MPS) method, and can be loaded using:
```

2024-12-13 18:35 UTC, AntonNI8 commented on doc/lightning_tensor/device.rst
> +By default, the device represents the quantum state approximated as a MPS.
```suggestion
By default, the device represents the quantum state approximated as an MPS.
```
Alternatively,
```suggestion
By default, the device approximates the quantum state using an MPS.
```
or,
```suggestion
By default, the device represents the quantum state via an MPS approximation.
```

2024-12-13 18:37 UTC, AntonNI8 commented on doc/lightning_tensor/device.rst
> +Users can not create a :class:`~pennylane.ops.op_math.Sum` observable or a :class:`~pennylane.ops.op_math.Prod` observable from :class:`~pennylane.ops.op_math.Sum` observables.
```suggestion
Users cannot create a :class:`~pennylane.ops.op_math.Sum` observable or a :class:`~pennylane.ops.op_math.Prod` observable from :class:`~pennylane.ops.op_math.Sum` observables.
```

2024-12-13 18:38 UTC, AntonNI8 approved these changes

2024-12-13 19:04 UTC, merged