Fix clang-tidy support for tests and extensibility
PennyLaneAI/pennylane-lightning pull request #237
Opened 2022-02-14 18:24 UTC by mlxd

**Context:** This closes #236 and #235 

**Description of the Change:** Clang-tidy is enabled for CI tests in the formatter action, and subsequent clang-tidy suggestions are applied. Also, The return type for data is modified to become auto-definable at compile time.

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

2022-02-14 21:35 UTC, mlxd commented
> Hi @mlxd, it seems like the current error is due to several unused parameters/variables. In the previous version, I have just suppressed those warnings (only for tests codes) by `-Wno-unused` as there are too many places with this warning and I thought they are not much harmful (even though some variables are unused, they provide some information e.g. `const auto num_qubits = 3;`). See the lines below.
> 
> https://github.com/PennyLaneAI/pennylane-lightning/blob/2cb27272c7882c5cf63a0ef047dc37884c113cac/pennylane_lightning/src/tests/CMakeLists.txt#L43-L45

Thanks @chaeyeunpark . I have added the casts to get over the failures for now. As discussed, we can look at adapting this to another structure later on.

2022-02-15 15:51 UTC, maliasadi approved these changes
Thanks @mlxd for fixing these issues.

2022-02-15 15:51 UTC, maliasadi commented on pennylane_lightning/src/tests/Test_DynamicDispatcher.cpp
> +      // pattern.
:100:

2022-02-15 16:36 UTC, chaeyeunpark requested changes
Hi @mlxd, thanks for dealing with this problem. Could you just check one thing here? If `clang-tidy` still complains about it, let's just remove this whole function (it anyway does nothing now...).

2022-02-15 17:01 UTC, mlxd commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
Hey @chaeyeunpark 

Ah, I understand your intention now. Yea, I was getting errors with these locally, and removed them based on the clang-tidy feedback. I'll re-add and retest with the `act` package, and if so we can leave them as deleted for now.

2022-02-15 17:24 UTC, mlxd commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
Huh, seems to be passing now (weird, may have been a version issue locally). I'll re-add this in and push it back up. Sorry for the confusion.

Update: scratch that, fails locally on clang-tidy-13

2022-02-15 17:24 UTC, mlxd commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
I will do some tests with different environments to see if this is an easy mitigation.

2022-02-15 17:54 UTC, chaeyeunpark commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
As it cannot be `nullptr` anyway, I think replacing the internal if statement just to 
```
static_cast<void>(GateOpToMemberFuncPtr<PrecisionT, ParamT, GateImplemenation, gate_op>::value);
```
will work.

2022-02-25 18:28 UTC, mlxd commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
Hey @chaeyeunpark sorry for taking so long to get back to this. That above suggestion does indeed fix the clang-tidy-13 complaint! Thanks for the suggestion.

2022-02-25 19:52 UTC, chaeyeunpark approved these changes
Happy to approve this :+1:

2022-02-25 19:52 UTC, chaeyeunpark commented on pennylane_lightning/src/tests/Test_OpToMemberFuncPtr.cpp
> -        }
Good!

2022-02-25 19:55 UTC, mlxd commented
Thanks @chaeyeunpark & @maliasadi

2022-02-25 19:55 UTC, merged